# Generated by Django 3.1.3 on 2020-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://pbs.twimg.com/profile_images/1023140866255249409/1CJ1vGU4_400x400.jpg', max_length=6000),
        ),
    ]
